settings:
  world-name: "world"
  min-radius: 100
  max-radius: 3000
  player-distance: 5
  countdown-seconds: 5

messages:
  prefix: "&#facc15[ᴀʀɪs ʀᴛᴘ] "
  help:
    - "&#facc15--- ᴀʀɪs ʀᴛᴘ ǫᴜᴇᴜᴇ ---"
    - "&#facc15/rtpq join &7- Tham gia hàng chờ"
    - "&#facc15/rtpq leave &7- Rời khỏi hàng chờ"
    - "&#facc15/rtpq reload &7- Tải lại cấu hình"
    - "&#facc15/rtpq world <tên> &7- Thiết lập thế giới RTP"
  joined-queue:
    text: "&aʙạɴ đã ᴛʜᴀᴍ ɢɪᴀ ʜàɴɢ ᴄʜờ!"
    chat: true
    actionbar: true
  left-queue:
    text: "&#ff0812ʙạɴ đã ʀờɪ ᴋʜỏɪ ʜàɴɢ ᴄʜờ!"
    chat: true
    actionbar: true
  already-in-queue:
    text: "&#ff0812Bạn đã ở trong hàng chờ rồi!"
    chat: true
  not-in-queue:
    text: "&#ff0812Bạn không có trong hàng chờ!"
    chat: true
  waiting-others:
    text: "&fđᴀɴɢ ᴄʜờ ᴛʜêᴍ ɴɢườɪ ʀᴛᴘǫᴜᴇᴜᴇ 1ᴠs1"
    chat: false
    actionbar: true
  broadcast-joined:
    text: "&#facc15%player% &fđã ᴛʜᴀᴍ ɢɪᴀ ʜàɴɢ ᴄʜờ ʀᴛᴘ"
    chat: true
  world-set:
    text: "&aĐã set &#facc15%world% &fthành điểm rtpqueue chính đã loại bỏ world cũ"
    chat: true
  world-not-found:
    text: "&#ff0812Không tìm thấy thế giới: &f%world%"
    chat: true
  countdown:
    text: "&7ᴅịᴄʜ ᴄʜᴜʏểɴ sᴀᴜ &#facc15%time%s"
    chat: true
    actionbar: true
  success:
    text: "&aᴅịᴄʜ ᴄʜᴜʏểɴ ᴛʜàɴɢ ᴄôɴɢ!"
    chat: true
    actionbar: true
  reload:
    text: "&aĐã tải lại cấu hình thành công!"
    chat: true

gui:
  title: "ʀᴛᴘǫᴜᴇᴜᴇ"
  items:
    cancel:
      slot: 10
      material: RED_STAINED_GLASS_PANE
      name: "&#ff0812ᴄᴀɴᴄᴇʟ"
      lore: "&fᴄʟɪᴄᴋ để ʀờɪ ʜàɴɢ ᴄʜờ"
    world:
      slot: 12
      material: GRASS_BLOCK
      name: "&#facc15ᴡᴏʀʟᴅ"
      lore: "&fᴛʜế ɢɪớɪ: &#facc15%world%"
    queue:
      slot: 13
      material: COMPASS
      name: "&#facc15ǫᴜᴇᴜᴇ"
      lore: "&fʜàɴɢ ᴄʜờ: &#facc15%count%/2"
    stats:
      slot: 14
      material: IRON_SWORD
      name: "&#facc15sᴛᴀᴛs"
      lore: "&fᴛʜôɴɢ ᴛɪɴ ᴄủᴀ ʙạɴ"
    confirm:
      slot: 16
      material: LIME_STAINED_GLASS_PANE
      name: "&2ᴄᴏɴғɪʀᴍ"
      lore: "&fᴄʟɪᴄᴋ để ᴛʜᴀᴍ ɢɪᴀ ʀᴛᴘ 1ᴠs1"
