settings:
  min-radius: 1000
  max-radius: 5000
  attempts: 15
  allowed-worlds:
    - world

sounds:
  click: "UI_BUTTON_CLICK"
  join: "ENTITY_EXPERIENCE_ORB_PICKUP"
  leave: "BLOCK_NOTE_BLOCK_BASS"
  teleport: "ENTITY_ENDERMAN_TELEPORT"
  error: "ENTITY_VILLAGER_NO"

gui:
  title: "&#ff0812&lᴀʀɪs ɴᴇᴛᴡᴏʀᴋ &8- &#facc15&lʀᴛᴘǫᴜᴇᴜᴇ"
  size: 27
  items:
    leave:
      slot: 10
      material: "RED_STAINED_GLASS_PANE"
      name: "&#ff0812&lᴄᴀɴᴄᴇʟ"
      lore: ["&fClick to cancel"]
    join:
      slot: 16
      material: "GREEN_STAINED_GLASS_PANE"
      name: "&asᴇᴀʀᴄʜ"
      lore: ["&fClick to find a match"]
    world:
      slot: 12
      material: "GRASS_BLOCK"
      name: "&#facc15&lᴡᴏʀʟᴅ"
      lore: ["&f%world%"]
    queue:
      slot: 13
      material: "COMPASS"
      name: "&#facc15&lǫᴜᴇᴜᴇ ᴘʟᴀʏᴇʀs"
      lore: ["&7Queue &f%count%/2"]
    ping:
      slot: 14
      material: "FEATHER"
      name: "&#facc15&lʀᴇɢɪᴏɴ"
      lore: ["&7Vietnam: (&#facc15%ping%ms)"]

messages:
  prefix: "&#ff0812&lᴀʀɪsʀᴛᴘǫ &8» "
  
  broadcast-join:
    text: "&fNgười chơi &#facc15%player% &fđã tham gia hàng chờ &#ff0812RTPQueue!"
    chat: true
    actionbar: false

  actionbar-waiting:
    text: "&#facc15Đang chờ thêm người tham gia... &7(%count%/2)"
    chat: false
    actionbar: true

  joined:
    text: "&fBạn đã &#facc15tham gia &fhàng chờ!"
    chat: true
    actionbar: true

  left:
    text: "&fBạn đã &#ff0812rời khỏi &fhàng chờ!"
    chat: true
    actionbar: true

  already-in-queue:
    text: "&cBạn đã ở trong hàng chờ trước đó rồi!"
    chat: true
    actionbar: false

  countdown-msg:
    text: "&fDịch chuyển trong: &#ff0812%time%s"
    chat: true
    actionbar: true

  no-safe-location:
    text: "&cKhông tìm thấy vị trí an toàn, vui lòng thử lại sau!"
    chat: true
    actionbar: true

  teleport-title: "&#ff0812&lʀᴛᴘǫᴜᴇᴜᴇ"
  teleport-subtitle: "&fĐã tìm thấy vị trí an toàn!"
  reload: "&aĐã tải lại cấu hình!"
