name: ArisRTPQueue
version: 1.4
main: me.aris.arisrtpqueue.ArisRTPQ
api-version: 1.20
author: VennLMAO
folia-supported: true
commands:
  rtpq:
    description: Aris Network RTP Queue
    aliases: [rtpqueue]
    usage: /rtpq [join|leave|help|reload|world]
permissions:
  rtpq.admin:
    description: Quyền quản trị cho ArisRTPQueue (reload, set world)
    default: op
